import Footer from "@/ui/Footer/Footer";
import Header from "@/ui/Header/Header";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ContactSection from "@/sections/ContactSection/ContactSection";

const popins = Poppins({
	subsets: ["latin"],
	weight: ["300", "500", "600", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pl" suppressHydrationWarning>
			<body className={`${popins.className} m-0 overflow-x-hidden bg-[#FAFAFA] p-0`}>
				<Header />
				{children}
				<ContactSection />
				<Footer />
			</body>
		</html>
	);
}
