import AOSProvider from "@/components/AOSProvider";
import { links } from "@/constants";
import ContactSection from "@/sections/ContactSection/ContactSection";
import Footer from "@/ui/Footer/Footer";
import Header from "@/ui/Header/Header";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { FacebookIcon, InstaIcon } from "../ui/Icons/icons";
import "./globals.css";

const popins = Poppins({
	subsets: ["latin"],
	weight: ["300", "500", "600", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pl" suppressHydrationWarning>
			<body className={`${popins.className} m-0 overflow-x-hidden bg-[#FAFAFA] p-0`}>
				<Header />
				<AOSProvider>{children}</AOSProvider>
				<ContactSection />
				<Footer />
				<div className="fixed bottom-4 right-2 z-30 flex flex-col gap-4">
					<a
						href={links.instagram}
						target="_blank"
						className="flex items-center justify-center rounded-full bg-primaryc p-4 shadow-lg"
					>
						<InstaIcon />
					</a>
					<a
						href={links.facebook}
						target="_blank"
						className="flex items-center justify-center rounded-full bg-primaryc p-4 shadow-lg"
					>
						<FacebookIcon />
					</a>
				</div>
			</body>
		</html>
	);
}
